---
title: "Multi-year trends"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide

---

```{r setup, message = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
options(scipen = 50)
library(ggplot2)
library(plotly)


theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d 
knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = 8,
  message = F,
  warning = F 
  )



```

We were also curious to see if there were any trends in time spent on different categories and plotted average time spent on activities from 2009 to 2019. While we don't see any obvious trends, the average time we spend on sleep seems to have been slightly increasing. 

```{r message = FALSE, echo = FALSE}

annual_data = read_csv("data/annual_activity.csv") 

annual_data_plotly = annual_data %>% 
  mutate(text_label = str_c("Activity: ", Activity, "\nEstimate: ", Estimate, "\nYear: ", Year)) %>%
  plot_ly(
    x = ~Year, y = ~Estimate, type = "scatter", mode = "line",
    color = ~Activity, text = ~text_label, alpha = 0.9) %>%
 layout(title = 'Average time spent on activities across the U.S. from 2009-2019', 
        xaxis = list(type = "category", title = 'Year'), 
        yaxis = list(title = 'Average Hours'))


```

```{r month_plot, echo = FALSE, message = FALSE, warning = FALSE}
annual_data_plotly
```



