---
title: "P8105 Final Project"
output: github_document
---

```{r setup, message = FALSE}
library(tidyverse)
options(scipen = 100)
knitr::opts_chunk$set(echo = TRUE)
```

## Read in the data
```{r}
resp_2019 = read.table("data/atusresp_2019.dat", header = TRUE, sep = ",")
resp_2020 = read.table("data/atusresp_2020.dat", header = TRUE, sep = ",")
roster_2019 = read.table("data/atusrost_2019.dat", header = TRUE, sep = ",")
roster_2020 = read.table("data/atusrost_2020.dat", header = TRUE, sep = ",")
roster_2019 = read.table("data/atusrost_2019.dat", header = TRUE, sep = ",")
roster_2020 = read.table("data/atusrost_2020.dat", header = TRUE, sep = ",")
who_2019 = read.table("data/atuswho_2019.dat", header = TRUE, sep = ",")
who_2020 = read.table("data/atuswho_2020.dat", header = TRUE, sep = ",")
activity_2019 = read.table("data/atusact_2019.dat", header = TRUE, sep = ",")
activity_2020 = read.table("data/atusact_2020.dat", header = TRUE, sep = ",")
activity_summary_2019 = read.table("data/atussum_2019.dat", header = TRUE, sep = ",")
activity_summary_2020 = read.table("data/atussum_2020.dat", header = TRUE, sep = ",")
```

```{r}
head(activity_2019)
```