---
title: "Project Report"
authors: Dee Wang (dtw2127), Sandya Ganesh (sg3891), Shaina Mackin (smm2350), Xin Fang (xf2226)
output: 
  html_document:
    toc: true
    toc_float: true
    source_code: embed 
---
</br>

# Project Motivation 
</p>
COVID-19 has drastically impacted the ways in which we spend our time. During the height of the pandemic, stay-at-home orders, lockdown measures, and social distancing norms prevented many Americans from going into workplaces and schools and from seeing friends and family, impacting the way we spend our days -- and making us hyper aware of that. The motivation for this project was originally to understand how COVID-19 affected time use. We set out to look at how time spent on activities such as paid and unpaid work, education, sleep, and leisure may have changed from pre- to post- pandemic, especially interested in understanding how changes in time use impact our general well-being.
</p>


# Related Work
The work that inspired this project was done by the [Our World in Data group](https://ourworldindata.org/time-use). They looked at how  people all around the world spend their days. They point out that looking at how we spend our time -- particularly focusing on how much time we spend on things we enjoy, can be informative about general well-being. In countries where individuals work more, and spend less time on leisure activities, there are lower levels of happiness and life satisfaction.</br>

A lot of individuals have used the specific datasets that we used for this project to do cool things! One example is a simulation built by a statistician at UCLA, who [simulated](https://flowingdata.com/2015/12/15/a-day-in-the-life-of-americans/) how 1000 Americans transition from one activity to another over the course of a day. We recommend you check it out.

# Initial Questions

The initial questions we had going into this project were:

**1.**  How do sociodemographic factors such as age, gender, occupation affect time spent on leisure activities and time spent with others? 

**2.** How does time use on different activities differ pre- and post-pandemic (2019 vs 2020)?

**3.** How do time use trends differ by geography and across the span of a decade?

We had initially planned to look at how sociodemographic factors affect time spent with others, however, obtaining an estimate of time spent with others ended up requiring some complex merging of datasets. We therefore decide to focus on time spent on various activity types, excluding time spent with others. As we conducted the regression analyses, we also had the idea to additionally look at the interaction of various sociodemographic variables, to see if there are any interaction effects for time spent on leisure activities.

•  How did these questions evolve over the course of the project? </br>
•  What new questions did you consider in the course of your analysis? </br>
</p>

# The Data
</p>
### Source: <br/>
Data for this project comes from the U.S. Bureau of Labor Statistics’ American Time Use Survey (ATUS), publicly available [here](https://www.bls.gov/tus/datafiles-2020.htm). </p> Key variables from the Activity Summary files included activity codes, total time spent on the activity, and demographic variables. We pulled dates of responses from the ATUS respondent files and geographic information from the CPS files.

### Cleaning: </br>
</p>

We started with the Activity Summary files. Our first step was to pivot from wide to long format, as the approximately 400 activity codes each had their own column. The activity codes (the letter "t" followed by 6 digits) were not very informative, so we also recoded them to be more informative of the activity (ex. t010101 was recoded as "Sleeping"). We categorized activity codes into 16 different categories (caring for and helping others, consumer purchases, eating and drinking, education, government services and civic obligations, household activities, household services, personal care, professional and personal care services, religious and spiritual, leisure, sports/exercise, telephone calls, traveling, volunteering and working) using the category definitions given by ATUS. We would like to note that some activities could have fallen under more than one category (ex. Some may view sports to fall under leisure and some may view it to fall under exercise or both). Other cleaning steps included renaming variable names to be more  informative (ex. TELFS renamed to labor_force_status).  We appended 2019 and 2020 datasets and merged the different datasets were using the ID (TUCASEID) variable. 


# Exploratory Analysis
•  Visualizations </br>
•  Summaries </br>
•  Exploratory statistical analyses </br>
•  Justify the steps you took, and show any major changes to your ideas </br>
</p>

# Statistical Analysis

We studied how various sociodemographic and other factors affected time spent on leisure activities. As the outcome was hours/day spent on leisure activities, we conducted linear regression. First, we looked at whether the predictor variables should be categorical or continuous. After plotting age against time spent on leisure activities, we saw a relatively linear association and no need for categorization. Race, originally had over 20 categories, so we grouped all mixed races into 1 category for ease of interpretation. We did not need to adjust the sex and employment status categorization. 

We explored whether there are differences in time spent on leisure activities in 2019 vs. 2020, as we have hypothesized that during the pandemic in 2020, people spent more on leisure activities, and found a significant difference. Leisure time spent in 2020 (post-pandemic) is  expected to be 0.237 hours longer per day than leisure time spent in 2019 on average.


Next, we created several linear regression models to test our various hypotheses around sociodemographic characteristics, and compared the fitted models in terms of their RSME values:

**(Model 1)**: Labor force status
Those who are employed and at work are expected to spend 1.4 fewer hours per day on leisure activities per day in comparison to those who are employed but absent from work, on average (p-value<0.05)

**(Model 2)**: Demographic characteristics: race, age, and sex. 
The 3 main effect predictors in Model 2 are all significant (p-value < 0.05). Specifically, for every 1 year increase in age, we expect people to spend 0.059 hours more on leisure activities per day on average, adjusting for race and sex. We expect males to spend 0.785 hours more on leisure activites per day on average, adjusting for race and age. Finally, those of Hawaiian/Pacific Islanders descent are expected to spend 1.02 hours more per day on leisure activities when compared to people of mixed race, while those who are Asian spend the least time on leisure activities on average, adjusting for sex and age. 

**(Model 3)**: Demographic characteristics: race, age, and sex, and their interactions. 
When interaction terms are added, race is no longer significant, and none of the interaction terms are significant (p-value > 0.05).

We found that Model 1 resulted in the lowest RSME values, which indicates that it is the best model, while Model 2 and Model 3 were similar in terms of RSME values.

# Discussion
•  What were your findings? </br>
•  Are they what you expect? </br>
•  What insights into the data can you make?</br>
